on:
  workflow_call:
    inputs:
      conan-profile:
        type: string
        required: true
      coverage:
        type: boolean
        required: true

jobs:
  windows-build-and-test:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v6

      - name: Setup Conan
        run: |
          pip install --upgrade pip
          pip install conan
          conan profile detect --force

      - name: Build
        run: conan build . --build=missing --profile=conan\profiles\${{inputs.conan-profile}}

      - name: Coverage
        if: inputs.coverage
        shell: cmd
        run: |
          if not exist coverage mkdir coverage
          dir /s /b build\*.profraw > coverage\profraws.txt
          dir /s /b build\unitTests.exe > coverage\unitTests.txt
          llvm-profdata merge -sparse @coverage\profraws.txt -o coverage\coverage.profdata
          llvm-cov export -format=lcov -instr-profile=coverage\coverage.profdata @coverage\unitTests.txt src > coverage\coverage.lcov
          llvm-cov show -format=html -instr-profile=coverage\coverage.profdata --output-dir=coverage @coverage\unitTests.txt src

      - name: Upload coverage
        if: inputs.coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{inputs.conan-profile}}
          path: coverage

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{inputs.conan-profile}}
          path: build/**/test-results*.xml
