# Trigger conditions
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Cancel competing runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  # Linter
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: clang-format
        run: |
          find src include tests \
          \( -name '*.c' -o -name '*.h' -o -name '*.cpp' -o -name '*.hpp' \) \
          -exec clang-format --style=file --dry-run --Werror {} +

  # Doxygen
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Run doxygen
        run: doxygen

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-html
          path: docs/html
          if-no-files-found: error

  # Linux builds
  linux-release:
    uses: ./.github/workflows/build-linux.yml
    permissions:
      contents: read
    with:
      conan-profile: linux-release

  linux-debug-clang:
    uses: ./.github/workflows/build-linux.yml
    permissions:
      contents: read
    with:
      conan-profile: linux-debug-clang
      clang-tidy: true

  linux-debug-coverage:
    uses: ./.github/workflows/build-linux.yml
    permissions:
      contents: read
    with:
      conan-profile: linux-debug-coverage
      coverage: true

  linux-debug-sanitizer:
    uses: ./.github/workflows/build-linux.yml
    permissions:
      contents: read
    with:
      conan-profile: linux-debug-sanitizer

  # Windows builds
  windows-release:
    uses: ./.github/workflows/build-windows.yml
    permissions:
      contents: read
    with:
      conan-profile: windows-release

  windows-debug:
    uses: ./.github/workflows/build-windows.yml
    permissions:
      contents: read
    with:
      conan-profile: windows-debug

  windows-clang-cov-san:
    uses: ./.github/workflows/build-windows.yml
    permissions:
      contents: read
    with:
      conan-profile: windows-clang-cov-san
      coverage: true
      clang-tidy: true

  # Publish Doxygen as GitHub Pages
  publish-docs:
    # Only when updating main
    if: github.event_name == 'push' && github.ref_name == 'main'
    needs:
      # Require checks to pass
      - lint
      - doxygen
      # Requires all builds to pass
      - linux-release
      - linux-debug-clang
      - linux-debug-coverage
      - linux-debug-sanitizer
      - windows-release
      - windows-debug
      - windows-clang-cov-san

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v4
        with:
          name: doxygen-html
          path: docs/html

      - uses: actions/configure-pages@v6

      - uses: actions/upload-pages-artifact@v5
        with:
          path: docs/html

      - id: deployment
        uses: actions/deploy-pages@v5
