# Trigger conditions
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Cancel competing runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  # Linter
  lint:
    uses: ./.github/workflows/linter.yml
    permissions:
      contents: read

  # Documentation
  docs-generate:
    uses: ./.github/workflows/docs-generate.yml
    permissions:
      contents: read

  # Linux builds
  linux-release:
    uses: ./.github/workflows/build-linux.yml
    permissions:
      contents: read
    with:
      conan-profile: linux-release

  linux-debug-clang:
    uses: ./.github/workflows/build-linux.yml
    permissions:
      contents: read
    with:
      conan-profile: linux-debug-clang
      clang-tidy: true

  linux-debug-coverage:
    uses: ./.github/workflows/build-linux.yml
    permissions:
      contents: read
    with:
      conan-profile: linux-debug-coverage
      coverage: true

  linux-debug-sanitizer:
    uses: ./.github/workflows/build-linux.yml
    permissions:
      contents: read
    with:
      conan-profile: linux-debug-sanitizer

  # Windows builds
  windows-release:
    uses: ./.github/workflows/build-windows.yml
    permissions:
      contents: read
    with:
      conan-profile: windows-release

  windows-debug:
    uses: ./.github/workflows/build-windows.yml
    permissions:
      contents: read
    with:
      conan-profile: windows-debug

  windows-clang-cov-san:
    uses: ./.github/workflows/build-windows.yml
    permissions:
      contents: read
    with:
      conan-profile: windows-clang-cov-san
      coverage: true
      clang-tidy: true

  # FreeBSD builds
  freebsd-release:
    uses: ./.github/workflows/build-freebsd.yml
    permissions:
      contents: read
    with:
      conan-profile: freebsd-release

  freebsd-debug-cov-san:
    uses: ./.github/workflows/build-freebsd.yml
    permissions:
      contents: read
    with:
      conan-profile: freebsd-debug-cov-san
      coverage: true
      clang-tidy: true

  # Publish Doxygen as GitHub Pages
  docs-publish:
    # Only when updating main
    if: github.event_name == 'push' && github.ref_name == 'main'
    needs:
      # Require checks to pass
      - lint
      - docs-generate
      # Requires all builds to pass
      - linux-release
      - linux-debug-clang
      - linux-debug-coverage
      - linux-debug-sanitizer
      - windows-release
      - windows-debug
      - windows-clang-cov-san
      - freebsd-release
      - freebsd-debug-cov-san

    uses: ./.github/workflows/docs-publish.yml

    permissions:
      contents: read
      pages: write
      id-token: write
